package com.patientmgmt.entity;

import java.time.LocalDate;

import java.time.LocalTime;
//Import statements
import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;


//Entity annotation marks this class as a JPA entity
@Entity
//Table annotation specifies the name of the database table for this entity
@Table(name = "Appointment")
public class Appointment {
	 // Id annotation specifies that this field is the primary key
  @Id
// GeneratedValue annotation indicates that the value for this field will be generated by the database
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long appointmentId; // Assuming the id is a Long type
  
  // Validation annotations to ensure that these fields are not empty
  @NotNull
  
  private LocalDate appointmentDate;// Use camelCase for variable names\
  
  @NotNull
  private LocalTime appointmentTime;
  @NotEmpty
  private String appointmentDuration;
  @NotEmpty
  private String appointmentReason;

  @ManyToOne
  @JoinColumn(name="patient_id")
  private Patient patient;

 @ManyToOne
 @JoinColumn(name="doc_id")
 private Doctor doctor;



  public Long getAppointmentId() {
      return appointmentId;
  }

  public void setAppointmentId(Long appointmentId) {
      this.appointmentId = appointmentId;
  }

  public Patient getPatient() {
      return patient;
  }

  public void setPatient(Patient patient) {
      this.patient = patient;
  }

  public Doctor getDoctor() {
      return doctor;
  }

  public void setDoctor(Doctor doctor) {
      this.doctor = doctor;
  }

  public Appointment() {
      // Default constructor
  }

  // Constructor with all fields
  public Appointment( Long appointmentId,LocalDate appointmentDate, LocalTime appointmentTime, String appointmentDuration, String appointmentReason) {
  	this.appointmentId = appointmentId;
      this.appointmentDate = appointmentDate;
      this.appointmentTime = appointmentTime;
      this.appointmentDuration = appointmentDuration;
      this.appointmentReason = appointmentReason;
  }

  // Getters and setters

  public Long getId() {
      return appointmentId;
  }

  public void setId(Long id) {
      this.appointmentId = id;
  }

  public @NotEmpty LocalDate getAppointmentDate() {
      return appointmentDate;
  }

  public void setAppointmentLocalDate(@NotEmpty LocalDate appointmentDate) {
      this.appointmentDate = appointmentDate;
  }

  public @NotEmpty LocalTime getAppointmentTime() {
      return appointmentTime;
  }

  public void setAppointmentLocalTime(@NotEmpty LocalTime appointmentTime) {
      this.appointmentTime = appointmentTime;
  }

  public String getAppointmentDuration() {
      return appointmentDuration;
  }

  public void setAppointmentDuration(String appointmentDuration) {
      this.appointmentDuration = appointmentDuration;
  }

  public String getAppointmentReason() {
      return appointmentReason;
  }

  public void setAppointmentReason(String appointmentReason) {
      this.appointmentReason = appointmentReason;
  }
  // toString method for easy debugging and logging
  @Override
  public String toString() {
      return "{appointmentId:" + appointmentId + ", appointmentDate:" + appointmentDate +
             ", appointmentTime:" + appointmentTime + ", appointmentDuration:" + appointmentDuration +
             ", appointmentReason:" + appointmentReason + "}";
  }
}


